org: msa0311
app: my-python-rest-api-app
service: my-python-rest-api-app

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
